### PR TITLE
fix lock scope

### PR DESCRIPTION
**Pull request by lgarithm**
The pair `(n_working, queue)` should be atomic, not `n_working` alone.

(After this fix, `n_working` doesn't need to be atomic any more).

### CODE REVIEW

**Comment by ganler** [comment]
I see. That's because I did not lock `wait_cv`.

**Comment by ganler** [comment]
I'll fix it now.

**Comment by ganler** [comment]
This is fixed in my newest PR in the main repo :)
I am closing this PR and thanks for your kind reminding.

**Comment by lgarithm** [comment]
<s>It still has deadlock.</s> (to be confirmed)

(The proposed fix is here: https://github.com/ganler/openpose-plus/pull/1/files, this will fix the deadlock)

**Comment by lgarithm** [comment]
It looks the deadlock happens less frequently after using the spinlock, but still possible to trigger with 
```bash

g++ -std=c++17 -O2 -pthread \
    examples/test_thread_pool.cpp \
    examples/thread_pool.cpp \
    examples/spinlock.cpp \
    -o test_thread_pool.out

for i in $(seq 1000); do
    ./test_thread_pool.out
done
```

and it gets 
```
[TEST FAILED] at line 137[TEST FAILED] at line 137[Bench = end]         @ Thread-Pool Qsort Test        (size = 4096):  For     <<< 50 >>> times, cost  <<<12.193>>> ms
```
sometimes.

**Comment by ganler** [comment]
@lgarithm Could you plz try my newest code again. (Now I tested it for 1000 times and no errors occur).

**Pull request closed without merging**
